import Foundation

public enum CodexMCPInstaller {
    public enum Result: Equatable, Sendable {
        case installed
        case updated
        case unchanged
        case skippedNoNode
        case skippedHarnessAbsent
        case failed(String)
    }

    private static let marker = "# Generated by Remarc - do not edit"
    private static let tableHeader = "[mcp_servers.remarc]"
    private static let nodePlaceholder = "<path-to-node>"
    private static let mcpPlaceholder = "<path-to-remarc-mcp>"

    public static func install(force: Bool = false) async -> Result {
        if !force {
            guard await SkillInstaller.Harness.codex.isPresent() else { return .skippedHarnessAbsent }
        }
        guard let nodePath = await BundledMCP.nodePath() else { return .skippedNoNode }
        guard let mcpPath = BundledMCP.mcpServerPath else { return .failed("bundled MCP script not found") }

        let dest = CodexLocations.configPath
        do {
            try FileManager.default.createDirectory(at: dest.deletingLastPathComponent(), withIntermediateDirectories: true)

            let priorText = (try? String(contentsOf: dest, encoding: .utf8)) ?? ""
            let newText = replacingRemarcConfig(in: priorText, nodePath: nodePath, mcpPath: mcpPath)

            if newText == priorText { return .unchanged }
            try writeAtomicallyWithBackup(newText, to: dest)
            debugLog("CodexMCPInstaller: installed MCP config at \(dest.path)")
            return priorText.isEmpty ? .installed : .updated
        } catch {
            debugLog("CodexMCPInstaller: \(error)")
            return .failed(error.localizedDescription)
        }
    }

    public static func uninstall() throws {
        let dest = CodexLocations.configPath
        guard let priorText = try? String(contentsOf: dest, encoding: .utf8) else { return }
        let newText = removingRemarcConfig(from: priorText)

        if newText.isEmpty {
            try FileManager.default.removeItem(at: dest)
        } else if newText != priorText {
            try writeAtomicallyWithBackup(newText + "\n", to: dest)
        }
    }

    public static func isInstalled() -> Bool {
        guard let text = try? String(contentsOf: CodexLocations.configPath, encoding: .utf8) else { return false }
        return text.contains(tableHeader)
    }

    public static func snippet(nodePath: String?, mcpPath: String?) -> String {
        renderBlock(nodePath: nodePath ?? nodePlaceholder, mcpPath: mcpPath ?? mcpPlaceholder)
    }

    static func replacingRemarcConfig(in text: String, nodePath: String, mcpPath: String) -> String {
        let scrubbed = stripRemarcTable(from: text)
        let freshBlock = renderBlock(nodePath: nodePath, mcpPath: mcpPath)
        return (scrubbed.isEmpty ? "" : scrubbed.trimmingTrailingNewlines() + "\n\n") + freshBlock + "\n"
    }

    static func removingRemarcConfig(from text: String) -> String {
        stripRemarcTable(from: text).trimmingTrailingNewlines()
    }

    static func stripRemarcTable(from text: String) -> String {
        var out: [String] = []
        var skipping = false

        for raw in text.components(separatedBy: "\n") {
            let trimmed = raw.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix(tableHeader) {
                while let last = out.last {
                    let lastTrimmed = last.trimmingCharacters(in: .whitespaces)
                    if lastTrimmed.isEmpty || lastTrimmed == marker {
                        out.removeLast()
                    } else {
                        break
                    }
                }
                skipping = true
                continue
            }

            if skipping && trimmed.hasPrefix("[") {
                skipping = false
            }

            if !skipping {
                out.append(raw)
            }
        }

        return out.joined(separator: "\n")
    }

    private static func renderBlock(nodePath: String, mcpPath: String) -> String {
        """
        \(marker)
        \(tableHeader)
        command = \(quote(nodePath))
        args = [\(quote(mcpPath))]
        """
    }

    private static func quote(_ value: String) -> String {
        "\"" + value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }

    private static func writeAtomicallyWithBackup(_ text: String, to dest: URL) throws {
        guard let data = text.data(using: .utf8) else {
            throw NSError(
                domain: "CodexMCPInstaller",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "could not encode UTF-8"]
            )
        }
        try writeAtomicallyWithBackup(data, to: dest)
    }

    private static func writeAtomicallyWithBackup(_ data: Data, to dest: URL) throws {
        let fm = FileManager.default
        let backup = dest.appendingPathExtension("backup")

        if fm.fileExists(atPath: backup.path) {
            try fm.removeItem(at: backup)
        }
        if fm.fileExists(atPath: dest.path) {
            try fm.copyItem(at: dest, to: backup)
        }

        do {
            try data.write(to: dest, options: .atomic)
        } catch {
            if fm.fileExists(atPath: backup.path) {
                _ = try? fm.replaceItemAt(dest, withItemAt: backup)
            }
            throw error
        }

        if fm.fileExists(atPath: backup.path) {
            try? fm.removeItem(at: backup)
        }
    }
}

extension String {
    func trimmingTrailingNewlines() -> String {
        var result = self
        while result.hasSuffix("\n") {
            result.removeLast()
        }
        return result
    }
}
