import Foundation
import Testing
@testable import RemarcFeature

@Suite("Codex MCP installer")
struct CodexMCPInstallerTests {
    @Test("Replacing Remarc TOML preserves unrelated tables and arrays")
    func replacingRemarcTablePreservesFollowingArrayTables() throws {
        let prior = """
        [other_setting]
        foo = "bar"

        # Generated by Remarc - do not edit
        [mcp_servers.remarc]
        command = "/old/path/node"
        args = ["/old/path/index.js"]

        [mcp_servers.something_else]
        command = "/usr/bin/true"

        [[some_array_of_tables]]
        name = "first"

        [[some_array_of_tables]]
        name = "second"
        """

        let updated = CodexMCPInstaller.replacingRemarcConfig(
            in: prior,
            nodePath: "/opt/homebrew/bin/node",
            mcpPath: "/Applications/Remarc.app/Contents/Resources/remarc-mcp.js"
        )

        #expect(updated.contains("[other_setting]"))
        #expect(updated.contains("[mcp_servers.something_else]"))
        #expect(updated.contains("[[some_array_of_tables]]"))
        #expect(updated.contains("name = \"first\""))
        #expect(updated.contains("name = \"second\""))
        #expect(!updated.contains("/old/path/node"))
        #expect(updated.components(separatedBy: "[mcp_servers.remarc]").count == 2)
    }

    @Test("Snippet uses placeholders before paths resolve")
    func snippetUsesPlaceholdersBeforePathsResolve() {
        let snippet = CodexMCPInstaller.snippet(nodePath: nil, mcpPath: nil)

        #expect(snippet.contains("command = \"<path-to-node>\""))
        #expect(snippet.contains("args = [\"<path-to-remarc-mcp>\"]"))
    }

    @Test("Removing Remarc TOML preserves unrelated MCP servers")
    func removingRemarcTablePreservesUnrelatedServers() {
        let prior = """
        [mcp_servers.keep_me]
        command = "/usr/bin/true"

        # Generated by Remarc - do not edit
        [mcp_servers.remarc]
        command = "/old/path/node"
        args = ["/old/path/index.js"]

        [ui]
        theme = "dark"
        """

        let updated = CodexMCPInstaller.removingRemarcConfig(from: prior)

        #expect(updated.contains("[mcp_servers.keep_me]"))
        #expect(updated.contains("[ui]"))
        #expect(!updated.contains("[mcp_servers.remarc]"))
        #expect(!updated.contains("# Generated by Remarc - do not edit"))
    }
}

@Suite("Cursor MCP installer")
struct CursorMCPInstallerTests {
    @Test("Merge preserves unrelated keys and MCP servers")
    func mergePreservesUnrelatedKeysAndServers() throws {
        let prior = """
        {
          "someUnrelatedKey": true,
          "mcpServers": {
            "another-server": {
              "command": "/foo"
            }
          }
        }
        """.data(using: .utf8)!

        let merged = try CursorMCPInstaller.mergedConfigData(
            priorData: prior,
            nodePath: "/opt/homebrew/bin/node",
            mcpPath: "/Applications/Remarc.app/Contents/Resources/remarc-mcp.js"
        )

        let root = try #require(JSONSerialization.jsonObject(with: merged) as? [String: Any])
        #expect(root["someUnrelatedKey"] as? Bool == true)

        let servers = try #require(root["mcpServers"] as? [String: Any])
        let other = try #require(servers["another-server"] as? [String: Any])
        #expect(other["command"] as? String == "/foo")

        let remarc = try #require(servers["remarc"] as? [String: Any])
        #expect(remarc["command"] as? String == "/opt/homebrew/bin/node")
        #expect(remarc["args"] as? [String] == ["/Applications/Remarc.app/Contents/Resources/remarc-mcp.js"])
    }

    @Test("Snippet uses placeholders before paths resolve")
    func snippetUsesPlaceholdersBeforePathsResolve() {
        let snippet = CursorMCPInstaller.snippet(nodePath: nil, mcpPath: nil)

        #expect(snippet.contains("\"command\" : \"<path-to-node>\""))
        #expect(snippet.contains("\"<path-to-remarc-mcp>\""))
    }

    @Test("Removing Remarc JSON preserves unrelated MCP servers")
    func removingRemarcJSONPreservesUnrelatedServers() throws {
        let prior = """
        {
          "mcpServers": {
            "another-server": {
              "command": "/foo"
            },
            "remarc": {
              "command": "/old/path/node",
              "args": ["/old/path/index.js"]
            }
          }
        }
        """.data(using: .utf8)!

        let updated = try CursorMCPInstaller.removingRemarcConfigData(priorData: prior)
        let root = try #require(JSONSerialization.jsonObject(with: updated) as? [String: Any])
        let servers = try #require(root["mcpServers"] as? [String: Any])

        #expect(servers["another-server"] != nil)
        #expect(servers["remarc"] == nil)
    }
}
